# This is a basic workflow to do scheduling in github actions. you can use "crontab.guru" to get schedule properly.  

name: Schedule File Skeleton

# Controls when the workflow will run
on:
# Triggers the workflow on a cron scheduled time.
  schedule:
  - cron: '0 23 * * *'

env:
  ORG_USERNAME:
  CONSUMER_KEY:
  SOURCE_BRANCH:
  TARGET_BRANCH:
  SOURCE_PATH:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    Deploy-schedule:
  # This workflow contains a single job called "run_scheduled_test"
    name: run-scheduled-test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: dev

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.